<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>dk.sdu.mmmi.cbse</groupId>
        <artifactId>asteroids.jpms</artifactId>
        <version>1.0.1-SNAPSHOT</version>
    </parent>
    <groupId>dk.sdu.mmmi.cbse</groupId>
    <artifactId>Player</artifactId>
    <version>1.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>Player</name>
    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>Common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>CommonBullet</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-self-to-mods</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>${project.groupId}</groupId>
                                    <artifactId>${project.artifactId}</artifactId>
                                    <version>${project.version}</version>
                                    <type>jar</type>
                                    <classifier></classifier>
                                </artifactItem>
                            </artifactItems>
                            <outputDirectory>${project.parent.basedir}/mods-mvn</outputDirectory>
                            <overWriteReleases>true</overWriteReleases>
                            <overWriteSnapshots>true</overWriteSnapshots>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <release>${maven.compiler.target}</release>
                </configuration>
                <executions>
                    <execution>
                        <id>default-testCompile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                        <configuration>
                            <compilerArgs>
                                <arg>--add-modules</arg>
                                <arg>org.junit.jupiter.api,org.junit.jupiter.engine,org.mockito,org.mockito.junit.jupiter,Common,CommonBullet</arg>
                                <arg>--release</arg>
                                <arg>${maven.compiler.target}</arg>
                            </compilerArgs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>
                        --module-path
                        "${project.build.directory}/test-libs${path.separator}${project.build.directory}/../Common/target/Common-${project.version}.jar${path.separator}${project.build.directory}/../CommonBullet/target/CommonBullet-${project.version}.jar"

                        --add-modules org.junit.jupiter.api,org.junit.jupiter.engine,org.mockito,org.mockito.junit.jupiter,Common,CommonBullet

                        --add-reads Player.test=Player

                        --add-opens Player/dk.sdu.mmmi.cbse.playersystem=org.junit.jupiter.api
                        --add-opens Player/dk.sdu.mmmi.cbse.playersystem=org.mockito
                        --add-opens Player/dk.sdu.mmmi.cbse.playersystem=org.mockito.junit.jupiter
                    </argLine>
                </configuration>
            </plugin>

        </plugins>
    </build>
</project>